# This file must exist and contain the variables for the fix to work.
repo_file: /etc/apt/sources.list.d/kubernetes.list
kubernetes_version: 1.33.0-1.1
repo_version: v1.32
new_repo_version: v1.33
kubeconfig_path: /home/sarvind/.kube/config
kubectl_binary_path: /home/sarvind/.local/bin/kubectl
